import { useId } from "react";
import { cn } from "@/lib/utils";

/**
 * KavaNow brand mark — solid amber squircle (amber-600 #d97706, matching the
 * `text-primary` wordmark) with a white amphora: the ancient Greek vessel that
 * shipped wine across the Mediterranean, i.e. the original κάβα logistics.
 * Mirrors public/favicon.svg (regenerated by scripts/generate-icons.sh — keep
 * the artwork in sync). Size it with a `size-*` / `h-* w-*` utility via
 * className.
 */
export function Logo({ className }: { className?: string }) {
  const maskId = useId();
  return (
    <svg
      viewBox="0 0 512 512"
      className={cn("size-8 shrink-0", className)}
      role="img"
      aria-label="KavaNow"
    >
      <defs>
        <mask id={maskId}>
          <rect width="512" height="512" fill="#fff" />
          {/* decorative pottery band — partial cut keeps the silhouette connected */}
          <rect x="194" y="302" width="124" height="11" rx="5.5" fill="#000" />
        </mask>
      </defs>
      <rect width="512" height="512" rx="112" fill="#d97706" />
      <g mask={`url(#${maskId})`} transform="translate(256 256) scale(1.08) translate(-256 -256)">
        {/* mouth */}
        <rect x="210" y="92" width="92" height="27" rx="13" fill="#fff" />
        {/* neck + body */}
        <path
          fill="#fff"
          d="M226 119 L286 119 C286 158 288 176 294 192 C336 208 352 226 352 254 C352 304 318 348 284 364 L284 382 L228 382 L228 364 C194 348 160 304 160 254 C160 226 176 208 218 192 C224 176 226 158 226 119 Z"
        />
        {/* foot */}
        <path
          fill="#fff"
          d="M230 390 L282 390 C282 400 290 405 302 408 C310 410 314 414 314 419 L198 419 C198 414 202 410 210 408 C222 405 230 400 230 390 Z"
        />
        {/* handles */}
        <g fill="none" stroke="#fff" strokeWidth="23" strokeLinecap="round">
          <path d="M286 148 C316 150 332 166 332 190 C332 216 320 232 300 242" />
          <path d="M226 148 C196 150 180 166 180 190 C180 216 192 232 212 242" />
        </g>
      </g>
    </svg>
  );
}
