import { useId } from "react";
import { cn } from "@/lib/utils";

/**
 * KavaNow brand mark — amber squircle with a white "KN" monogram.
 * Mirrors public/favicon.svg (regenerated by scripts/generate-icons.sh).
 * Size it with a `size-*` / `h-* w-*` utility via className.
 */
export function Logo({ className }: { className?: string }) {
  const gradientId = useId();
  return (
    <svg
      viewBox="0 0 512 512"
      className={cn("size-8 shrink-0", className)}
      role="img"
      aria-label="KavaNow"
    >
      <defs>
        <linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#f59e0b" />
          <stop offset="1" stopColor="#d97706" />
        </linearGradient>
      </defs>
      <rect width="512" height="512" rx="112" fill={`url(#${gradientId})`} />
      <g fill="none" stroke="#ffffff" strokeWidth="42" strokeLinecap="round" strokeLinejoin="round">
        <path d="M126 165V347" />
        <path d="M221 165L141 256 221 347" />
        <path d="M296 347L296 165 386 347 386 165" />
      </g>
    </svg>
  );
}
