/**
 * Shared API error codes — backend sends them on 4xx responses, frontend
 * maps them to localized user-facing messages. The backend `error` field
 * stays English (developer/log-facing); translation lives in the frontend.
 */
export const API_ERROR_CODES = {
  // Unique-violation codes
  DUPLICATE_CUSTOMER_ERP_REF: "DUPLICATE_CUSTOMER_ERP_REF",
  DUPLICATE_PRODUCT_ERP_REF: "DUPLICATE_PRODUCT_ERP_REF",
  DUPLICATE_PRODUCT_NAME_BRAND: "DUPLICATE_PRODUCT_NAME_BRAND",
  DUPLICATE_CATEGORY_NAME: "DUPLICATE_CATEGORY_NAME",
  DUPLICATE_TENANT_SLUG: "DUPLICATE_TENANT_SLUG",
  DUPLICATE_USER_EMAIL: "DUPLICATE_USER_EMAIL",
  DUPLICATE_TENANT_MEMBERSHIP: "DUPLICATE_TENANT_MEMBERSHIP",

  // Order / order-item state
  ORDER_LOCKED_BY_STATUS: "ORDER_LOCKED_BY_STATUS",
  ORDER_LOCKED_BY_ERP: "ORDER_LOCKED_BY_ERP",
  ORDER_ALREADY_TRANSMITTED: "ORDER_ALREADY_TRANSMITTED",
  ORDER_ITEM_CANCELLED: "ORDER_ITEM_CANCELLED",
  ORDER_INVALID_STATUS: "ORDER_INVALID_STATUS",
  PRODUCT_NOT_AVAILABLE: "PRODUCT_NOT_AVAILABLE",
  REPLACEMENT_PRODUCT_NOT_AVAILABLE: "REPLACEMENT_PRODUCT_NOT_AVAILABLE",

  // Delete blocked by FK references
  CATEGORY_HAS_PRODUCTS: "CATEGORY_HAS_PRODUCTS",

  // Membership / user management
  CUSTOMER_HAS_ORDERS: "CUSTOMER_HAS_ORDERS",
  USER_ALREADY_ACTIVATED: "USER_ALREADY_ACTIVATED",
  CANT_DELETE_SELF: "CANT_DELETE_SELF",
  LAST_OWNER_PROTECTION: "LAST_OWNER_PROTECTION",
  ONLY_OWNER_CAN_PROMOTE: "ONLY_OWNER_CAN_PROMOTE",
  ONLY_OWNER_CAN_DELETE_OWNER: "ONLY_OWNER_CAN_DELETE_OWNER",
  ONLY_STAFF_PROMOTABLE: "ONLY_STAFF_PROMOTABLE",

  // Customer-side
  CUSTOMER_PROFILE_MISSING: "CUSTOMER_PROFILE_MISSING",
  ORIGINAL_ITEMS_UNAVAILABLE: "ORIGINAL_ITEMS_UNAVAILABLE",
  ORDER_EMPTY: "ORDER_EMPTY",

  // Misc
  NO_UPDATE_FIELDS: "NO_UPDATE_FIELDS",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export interface ApiErrorBody {
  /** Stable machine-readable code; frontend translates to a user-facing message. */
  code?: ApiErrorCode;
  /** English description for logs / developer tooling. */
  error: string;
}
