export interface DemoProduct {
  name: string;
  brand?: string | null;
  categoryName: string;
  description?: string | null;
  imageUrl?: string | null;
  volumeMl?: number | null;
  alcoholPct?: string | null;
  unit: "bottle" | "case" | "keg";
}

export const DEMO_PRODUCTS: DemoProduct[] = [
  // Κρασιά (Wines)
  {
    name: "Αγιωργίτικο",
    brand: "Νεμέα Σκούρας",
    categoryName: "Κρασιά",
    description: "Ερυθρό ξηρό κρασί ΠΟΠ Νεμέα",
    volumeMl: 750,
    alcoholPct: "13.0",
    unit: "bottle",
  },
  {
    name: "Ασύρτικο",
    brand: "Σιγάλας",
    categoryName: "Κρασιά",
    description: "Λευκό ξηρό κρασί Σαντορίνης",
    volumeMl: 750,
    alcoholPct: "13.5",
    unit: "bottle",
  },
  {
    name: "Μοσχοφίλερο",
    brand: "Μπουτάρη",
    categoryName: "Κρασιά",
    description: "Λευκό ξηρό κρασί Μαντινείας",
    volumeMl: 750,
    alcoholPct: "12.0",
    unit: "bottle",
  },
  {
    name: "Ξινόμαυρο",
    brand: "Κυρ-Γιάννη",
    categoryName: "Κρασιά",
    description: "Ερυθρό ξηρό κρασί Νάουσας",
    volumeMl: 750,
    alcoholPct: "13.5",
    unit: "bottle",
  },
  {
    name: "Ρετσίνα",
    brand: "Μαλαματίνα",
    categoryName: "Κρασιά",
    description: "Λευκό ρητινίτης οίνος",
    volumeMl: 500,
    alcoholPct: "11.5",
    unit: "bottle",
  },
  {
    name: "Ροζέ",
    brand: "Λαζαρίδη",
    categoryName: "Κρασιά",
    description: "Ροζέ ξηρό κρασί Δράμας",
    volumeMl: 750,
    alcoholPct: "12.5",
    unit: "bottle",
  },

  // Μπύρες (Beers)
  {
    name: "Μύθος",
    brand: "Olympic Brewery",
    categoryName: "Μπύρες",
    description: "Ελληνική lager μπύρα",
    volumeMl: 330,
    alcoholPct: "5.0",
    unit: "bottle",
  },
  {
    name: "Fix Hellas",
    brand: "Olympic Brewery",
    categoryName: "Μπύρες",
    description: "Premium lager μπύρα",
    volumeMl: 330,
    alcoholPct: "5.0",
    unit: "bottle",
  },
  {
    name: "Άλφα",
    brand: "Athenian Brewery",
    categoryName: "Μπύρες",
    description: "Ελληνική lager μπύρα",
    volumeMl: 330,
    alcoholPct: "5.0",
    unit: "bottle",
  },
  {
    name: "Βεργίνα",
    brand: "Μακεδονική Θράκης",
    categoryName: "Μπύρες",
    description: "Premium lager μπύρα",
    volumeMl: 330,
    alcoholPct: "5.0",
    unit: "bottle",
  },
  {
    name: "Νήσος",
    brand: "Νήσος",
    categoryName: "Μπύρες",
    description: "Craft pilsner Τήνου",
    volumeMl: 330,
    alcoholPct: "5.0",
    unit: "bottle",
  },
  {
    name: "Septem Μέρες",
    brand: "Septem",
    categoryName: "Μπύρες",
    description: "Craft pilsner Εύβοιας",
    volumeMl: 330,
    alcoholPct: "5.0",
    unit: "bottle",
  },

  // Αποστάγματα (Spirits)
  {
    name: "Ούζο 12",
    brand: "Ούζο 12",
    categoryName: "Αποστάγματα",
    description: "Κλασικό ελληνικό ούζο",
    volumeMl: 700,
    alcoholPct: "40.0",
    unit: "bottle",
  },
  {
    name: "Ούζο Πλωμαρίου",
    brand: "Βαρβαγιάννη",
    categoryName: "Αποστάγματα",
    description: "Ούζο Λέσβου",
    volumeMl: 700,
    alcoholPct: "40.0",
    unit: "bottle",
  },
  {
    name: "Τσίπουρο",
    brand: "Τσιλιλή",
    categoryName: "Αποστάγματα",
    description: "Τσίπουρο Τυρνάβου χωρίς γλυκάνισο",
    volumeMl: 700,
    alcoholPct: "40.0",
    unit: "bottle",
  },
  {
    name: "Τσίπουρο με γλυκάνισο",
    brand: "Τσιλιλή",
    categoryName: "Αποστάγματα",
    description: "Τσίπουρο Τυρνάβου με γλυκάνισο",
    volumeMl: 700,
    alcoholPct: "42.0",
    unit: "bottle",
  },
  {
    name: "Μεταξά 5*",
    brand: "Μεταξά",
    categoryName: "Αποστάγματα",
    description: "Ελληνικό brandy 5 αστέρων",
    volumeMl: 700,
    alcoholPct: "38.0",
    unit: "bottle",
  },
  {
    name: "Μεταξά 7*",
    brand: "Μεταξά",
    categoryName: "Αποστάγματα",
    description: "Ελληνικό brandy 7 αστέρων",
    volumeMl: 700,
    alcoholPct: "40.0",
    unit: "bottle",
  },

  // Λικέρ (Liqueurs)
  {
    name: "Μαστίχα Χίου",
    brand: "Σκίνος",
    categoryName: "Λικέρ",
    description: "Λικέρ μαστίχας Χίου",
    volumeMl: 700,
    alcoholPct: "30.0",
    unit: "bottle",
  },
  {
    name: "Τεντούρα",
    brand: "Αχάϊα",
    categoryName: "Λικέρ",
    description: "Παραδοσιακό λικέρ Πάτρας",
    volumeMl: 500,
    alcoholPct: "25.0",
    unit: "bottle",
  },
  {
    name: "Κίτρο Νάξου",
    brand: "Βαλλίνδρα",
    categoryName: "Λικέρ",
    description: "Λικέρ κίτρου Νάξου",
    volumeMl: 500,
    alcoholPct: "36.0",
    unit: "bottle",
  },
  {
    name: "Ρακόμελο",
    brand: "Κρητικό",
    categoryName: "Λικέρ",
    description: "Ρακί με μέλι Κρήτης",
    volumeMl: 500,
    alcoholPct: "25.0",
    unit: "bottle",
  },

  // Αναψυκτικά (Soft Drinks)
  {
    name: "Coca-Cola",
    brand: "Coca-Cola",
    categoryName: "Αναψυκτικά",
    description: "Κλασική Coca-Cola",
    volumeMl: 330,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Coca-Cola Zero",
    brand: "Coca-Cola",
    categoryName: "Αναψυκτικά",
    description: "Coca-Cola χωρίς ζάχαρη",
    volumeMl: 330,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Sprite",
    brand: "Coca-Cola",
    categoryName: "Αναψυκτικά",
    description: "Ανθρακούχο λεμόνι",
    volumeMl: 330,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Fanta Πορτοκάλι",
    brand: "Coca-Cola",
    categoryName: "Αναψυκτικά",
    description: "Ανθρακούχο πορτοκάλι",
    volumeMl: 330,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Schweppes Tonic",
    brand: "Schweppes",
    categoryName: "Αναψυκτικά",
    description: "Τόνικ γουότερ",
    volumeMl: 330,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Schweppes Σόδα",
    brand: "Schweppes",
    categoryName: "Αναψυκτικά",
    description: "Σόδα",
    volumeMl: 330,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Λεμονίτα Λουξ",
    brand: "Λουξ",
    categoryName: "Αναψυκτικά",
    description: "Ελληνική λεμονάδα",
    volumeMl: 330,
    alcoholPct: null,
    unit: "bottle",
  },

  // Νερά (Water)
  {
    name: "Ζαγόρι",
    brand: "Ζαγόρι",
    categoryName: "Νερά",
    description: "Φυσικό μεταλλικό νερό",
    volumeMl: 500,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Ζαγόρι Ανθρακούχο",
    brand: "Ζαγόρι",
    categoryName: "Νερά",
    description: "Φυσικό ανθρακούχο νερό",
    volumeMl: 750,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Βίκος",
    brand: "Βίκος",
    categoryName: "Νερά",
    description: "Φυσικό μεταλλικό νερό",
    volumeMl: 500,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "ΑΥΡΑ",
    brand: "ΑΥΡΑ",
    categoryName: "Νερά",
    description: "Φυσικό μεταλλικό νερό",
    volumeMl: 500,
    alcoholPct: null,
    unit: "bottle",
  },

  // Χυμοί (Juices)
  {
    name: "Πορτοκάλι",
    brand: "Λακωνία",
    categoryName: "Χυμοί",
    description: "Φυσικός χυμός πορτοκάλι",
    volumeMl: 250,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Ροδάκινο",
    brand: "Λακωνία",
    categoryName: "Χυμοί",
    description: "Νέκταρ ροδάκινο",
    volumeMl: 250,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Βύσσινο",
    brand: "Λακωνία",
    categoryName: "Χυμοί",
    description: "Νέκταρ βύσσινο",
    volumeMl: 250,
    alcoholPct: null,
    unit: "bottle",
  },
  {
    name: "Λεμόνι",
    brand: "Λακωνία",
    categoryName: "Χυμοί",
    description: "Φυσικός χυμός λεμόνι",
    volumeMl: 250,
    alcoholPct: null,
    unit: "bottle",
  },
];
